In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [2]:
# Sum — np.sum()
print(np.sum(arr))

150


In [3]:
# Mean — np.mean()
print(np.mean(arr))

30.0


In [4]:
# Median — np.median()
print(np.median(arr))

30.0


In [5]:
# Minimum — np.min()
print(np.min(arr))

10


In [6]:
# Maximum — np.max()
print(np.max(arr))

50


# Range
- Range = Maximum − Minimum

In [7]:
print(np.max(arr)-np.min(arr))

40


# Standard Deviation — np.std()

In [9]:
arr1=np.array([10,20,30,40,50,60,70])
print(np.std(arr))

14.142135623730951


# Variance — np.var()

In [10]:
print(np.var(arr1))

400.0


# Percentile

In [13]:
arr2=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.percentile(arr2,25))

32.5


In [14]:
print(np.percentile(arr2,50))

55.0


In [16]:
print(np.percentile(arr2,70))

73.0


# np.argmax()
- Find the index of the maximum value.

In [17]:
arr=np.array([10,20,30,40,50])
print(np.argmax(arr))

4


In [20]:
arr = np.array([10, 50, 20, 80, 30])
print(np.argmax(arr))

3


# np.argmin()
- Find the index of the minimum value

In [23]:
arr=np.array([10,20,30,40,4,40,30])
print(np.argmin(arr))

4


# 2D Array

In [26]:
sales=np.array([
    [100,200,300],
    [400,500,600],
    [700,800,900]])
print(sales)

[[100 200 300]
 [400 500 600]
 [700 800 900]]


In [27]:
# Total of all values
print(np.sum(sales))

4500


# axis=0

In [29]:
print(np.sum(sales,axis=0))

[1200 1500 1800]


# axis=1

In [30]:
print(np.sum(sales,axis=1))

[ 600 1500 2400]


# Column Average

In [31]:
print(np.mean(sales,axis=0))

[400. 500. 600.]


# Row Average

In [32]:
print(np.mean(sales,axis=1))

[200. 500. 800.]


# Column Maximum

In [33]:
print(np.max(sales,axis=0))

[700 800 900]


# Row Maximum

In [34]:
print(np.max(sales,axis=1))

[300 600 900]


In [37]:
print(np.sum(sales, axis=0))

[1200 1500 1800]
