In [3]:
import numpy as np

In [9]:
arr=np.array([10,20,30,30,40,50,60,70])
print(arr)
print(len(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

[10 20 30 30 40 50 60 70]
8
int64
(8,)
8


# Addition
- Add 5 to every element:

In [11]:
print(arr+5)

[15 25 35 35 45 55 65 75]


# Two arrays

In [13]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,3])
print(arr1+arr2)

[11 22 33 43]


# Subtraction

In [15]:
print(arr-5)

[ 5 15 25 25 35 45 55 65]


# Two arrays:

In [16]:
print(arr1-arr2)

[ 9 18 27 37]


# Multiplication

In [17]:
print(arr*2)

[ 20  40  60  60  80 100 120 140]


# Two arrays:

In [18]:
print(arr1*arr2)

[ 10  40  90 120]


# Division

In [20]:
print(arr/10)

[1. 2. 3. 3. 4. 5. 6. 7.]


# Power

In [22]:
print(arr**2)

[ 100  400  900  900 1600 2500 3600 4900]


# Modulus %
- Modulus gives the remainde

In [24]:
number=np.array([10,15,20,25,30])
print(number%10)

[0 5 0 5 0]


# np.add()

In [25]:
print(np.add(arr1,arr2))

[11 22 33 43]


# np.subtract()

In [26]:
print(np.subtract(arr1,arr2))

[ 9 18 27 37]


# np.multiply()

In [27]:
print(np.multiply(arr1,arr2))

[ 10  40  90 120]


# np.divide()

In [28]:
print(np.divide(arr1,arr2))

[10.         10.         10.         13.33333333]


# Sum
- np.sum() gives the total.

In [32]:
arr=np.array([10,20,30,40,50,60,70])
print(arr)
print(np.sum(arr))

[10 20 30 40 50 60 70]
280


# Mean
- np.mean() gives the average.

In [35]:
print(arr)
print(np.mean(arr))

[10 20 30 40 50 60 70]
40.0


# Minimum

In [37]:
print(arr)
print(np.min(arr))

[10 20 30 40 50 60 70]
10


# Maximum

In [39]:
print(arr)
print(np.max(arr))

[10 20 30 40 50 60 70]
70


# Standard Deviation

In [41]:
print(arr)
print(np.std(arr))

[10 20 30 40 50 60 70]
20.0


# Variance

In [43]:
print(arr)
print(np.var(arr))

[10 20 30 40 50 60 70]
400.0


# Square Root

In [45]:
print(arr)
print(np.sqrt(arr))

[10 20 30 40 50 60 70]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027]


# Absolute Value

In [49]:
arr = np.array([-10, -20, 30, -40])
print(np.abs(arr))

[10 20 30 40]


# np.power()

In [53]:
arr=np.array([1,2,3,4,5])
print(np.power(arr,2))

[ 1  4  9 16 25]


# 2D Array Operations

In [55]:
arr=np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(np.sum(arr))

36


In [56]:
print(np.sum(arr, axis=0))

[ 6  8 10 12]
