# NumPy Boolean Indexing & Filtering

In [4]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70])
print(arr>25)

[False False  True  True  True  True  True]


# Filter values greater than 30

In [6]:
print(arr>30)

[False False False  True  True  True  True]


# Values less than 30

In [7]:
print(arr[arr<30])

[10 20]


# Values greater than or equal to 30

In [9]:
print(arr[arr>=30])

[30 40 50 60 70]


# Values less than or equal to 30

In [10]:
print(arr[arr<=30])

[10 20 30]


# Equal to a value

In [16]:
arr1=np.array([10,20,30,30,40,50,30])
print(arr1[arr1==30])

[30 30 30]


# Not Equal !=

In [17]:
print(arr[arr!=30])

[10 20 40 50 60 70]


# Filter Even Numbers

In [20]:
arr2=np.array([11,12,13,14,15,16,17,18,19,20])
print(arr2)
print(arr2[arr2%2==0])

[11 12 13 14 15 16 17 18 19 20]
[12 14 16 18 20]


In [21]:
# Filter Odd Numbers
print(arr2[arr2%2!=0])

[11 13 15 17 19]


# Multiple Conditions — AND &
- Suppose we want values:
- greater than 20
- AND
- less than 40

In [25]:
arr=np.array([10,20,25,30,35,40,45])
result=arr[(arr>20)&(arr<40)]
print(result)

[25 30 35]


# OR |
- Suppose:
- less than 20
- OR
- greater than 40

In [27]:
result=arr[(arr<20)|(arr>40)]
print(result)

[10 45]


# NOT ~
- Suppose we don't want values greater than 30.

In [28]:
result = arr[~(arr > 30)]
print(result)

[10 20 25 30]


# Real-Life Example — Student Marks

In [30]:
marks = np.array([35, 45, 67, 89, 92, 28, 76, 55, 40])
print(marks)

[35 45 67 89 92 28 76 55 40]


# Students who passed
- Assume passing mark = 40:

In [32]:
passed=marks[marks>40]
print(passed)

[45 67 89 92 76 55]


In [34]:
# Students who failed
failed=marks[marks<40]
print(failed)

[35 28]


In [36]:
# Students who scored 80+
top_student=marks[marks>80]
print(top_student)

[89 92]


# Marks between 50 and 80

In [39]:
result = marks[(marks >= 50) & (marks <= 80)]
print(result)

[67 76 55]


# Real-Life Example — Salaries

In [41]:
salary = np.array([
    25000,
    35000,
    45000,
    55000,
    65000,
    75000,
    90000])
print(salary)

[25000 35000 45000 55000 65000 75000 90000]


In [43]:
# Salary > ₹50,000
print(salary[salary > 50000])

[55000 65000 75000 90000]


In [46]:
# Salary between ₹40,000 and ₹70,000
result = salary[(salary >= 40000) & (salary <= 70000)]
print(result)

[45000 55000 65000]


# Real-Life Example — Product Prices

In [49]:
prices = np.array([
    500,
    1200,
    2500,
    800,
    3500,
    1500])
print(prices)

[ 500 1200 2500  800 3500 1500]


In [50]:
# Products above ₹1,000
print(prices[prices>1000])

[1200 2500 3500 1500]


In [51]:
# Products below ₹1,000
print(prices[prices<1000])

[500 800]


# 2D Array Filtering

In [54]:
marks = np.array([
    [80, 70, 90],
    [60, 50, 65],
    [95, 88, 92]])
print(marks)

[[80 70 90]
 [60 50 65]
 [95 88 92]]


In [55]:
# Find values greater than 80:
print(marks[marks>80])

[90 95 88 92]


# Replace Values Using Conditions
- Suppose marks below 40 should become 0.

In [57]:
marks = np.array([35, 45, 67, 28, 90])
marks[marks < 40] = 0
print(marks)

[ 0 45 67  0 90]


# np.where() 
- np.where() is used for conditional replacement.

In [58]:
marks = np.array([35, 45, 67, 28, 90])
result=np.where(marks>=40,"Pass","Faile")
print(result)

['Faile' 'Pass' 'Pass' 'Faile' 'Pass']


# np.where() Real Example

In [60]:
salary = np.array([25000, 45000, 65000, 30000, 80000])
result = np.where(salary >= 50000, "High", "Low")
print(result)

['Low' 'Low' 'High' 'Low' 'High']
