# 1. Create a 1D array

In [2]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
import numpy as np
arr=np.array([100,200,300,400,500])
arr

array([100, 200, 300, 400, 500])

# 2. Access first element
- Python indexing starts from 0.

In [4]:
print(arr[0])

100


# 3. Access specific elements

In [7]:
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

200
300
400
500


# 4. Negative indexing
- -1 means the last element.

In [8]:
print(arr[-1])

500


In [9]:
print(arr[-2])

400


In [10]:
print(arr[-3])

300


# 5. 2D Array Indexing

In [13]:
import numpy as np
arr2=np.array([
    [10,20,30,],
    [40,50,60],
    [70,80,90]])
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
# Access 10
print(arr2[0,0])

10


In [19]:
# Access 50
print(arr2[1,1])

50


In [20]:
# Access 90
print(arr2[2,2])

90


# 6. Access a complete row
- First row:

In [21]:
print(arr2[0])

[10 20 30]


In [23]:
# Second row:
print(arr2[1])

[40 50 60]


In [24]:
print(arr2[-1])

[70 80 90]


# 7. Access a complete column
- First column:

In [25]:
print(arr2[:,0])

[10 40 70]


In [26]:
# Second column:
print(arr2[:,1])

[20 50 80]


In [28]:
print(arr2[:,-1])

[30 60 90]
