# Day 02 — NumPy Array Creation

In [1]:
import numpy as np

# np.zeros()
- Creates an array filled with 0.

In [4]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [9]:
arr=np.zeros(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


# 2D zeros

In [13]:
arr=np.zeros((3,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
arr=np.zeros((4,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 3. np.ones()
- Creates an array filled with 1.

In [51]:
arr=np.ones(3)
arr

array([1., 1., 1.])

In [53]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

# 2D:

In [55]:
arr=np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
arr=np.ones((3,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# 3. np.arange()
- Creates numbers within a given range.

In [22]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- With step:

In [25]:
arr=np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# 4. np.linspace()
- Creates evenly spaced numbers.

In [27]:
arr=np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

- Difference:
- arange  → step-based
- linspace → number-of-values based

# 5.np.full()
- Creates an array with the same value.

In [32]:
arr=np.full(5,28)
arr

array([28, 28, 28, 28, 28])

In [34]:
arr=np.full(5,7)
arr

array([7, 7, 7, 7, 7])

In [38]:
arr=np.full(7,26)
arr

array([26, 26, 26, 26, 26, 26, 26])

# 2D

In [41]:
arr=np.full((3,3),7)
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [43]:
arr=np.full((4,4),28)
arr

array([[28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28]])

In [46]:
arr=np.full((3,3),10)
arr

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# 6. np.eye()
- Creates an identity matrix.

In [48]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])