# NumPy Sorting, Searching & Unique Values

# 1️ np.sort() — Sort values

In [7]:
import numpy as np
arr=np.array([10,20,10,40,50,15,25,54])
result=np.sort(arr)
print(arr)

[10 20 10 40 50 15 25 54]


In [11]:
print(np.sort(arr)[::-1])

[54 50 40 25 20 15 10 10]


In [12]:
import numpy as np
arr=[10,30,301,30,10,3,20,40]
result=np.sort(arr)
print(result)

[  3  10  10  20  30  30  40 301]


# Descending order

In [14]:
print(np.sort(arr)[::-1])

[301  40  30  30  20  10  10   3]


# Original array doesn't change

In [17]:
arr=np.array([10,20,30,10,40,50,50,80,43])
result=np.sort(arr)
print("Original_array:",arr)
print("Sorted:",result)

Original_array: [10 20 30 10 40 50 50 80 43]
Sorted: [10 10 20 30 40 43 50 50 80]


# arr.sort()

In [19]:
arr=[12,14,1,4,6,7,8,1,5,2]
arr.sort()
print(arr)

[1, 1, 2, 4, 5, 6, 7, 8, 12, 14]


# np.argsort()
- argsort() gives the index positions that would sort the array.

In [22]:
arr = np.array([50, 20, 80, 10, 40])
result=np.argsort(arr)
print(result)

[3 1 4 0 2]


# Use argsort() to sort another array

In [26]:
name=np.array(["A","B","C","D"])
marks=np.array([80,60,76,98])
result=np.argsort(marks)
print(result)

print(name[result])
print(marks[result])

[1 2 0 3]
['B' 'C' 'A' 'D']
[60 76 80 98]


# Descending with argsort()

In [28]:
indices = np.argsort(marks)[::-1]

print(name[indices])
print(marks[indices])

['D' 'A' 'C' 'B']
[98 80 76 60]


# np.unique() 
- unique() gives only unique values.

In [29]:
arr=np.array([10,20,10,20,30,304,10,30,40,50,40,60])
result=np.unique(arr)
print(result)

[ 10  20  30  40  50  60 304]


# Count unique values

In [33]:
arr=np.array(["Python", "SQL", "Python", "Excel", "SQL", "Python"])
values,counts=np.unique(arr,return_counts=1)
print("Values:",values)
print("counts:",counts)

Values: ['Excel' 'Python' 'SQL']
counts: [1 3 2]


# Find positions using np.where()

In [34]:
arr=np.array([10,20,30,10,40,50])
print(np.where(arr>25))

(array([2, 4, 5]),)


In [37]:
result=np.where(arr>20)[0]
result

array([2, 4, 5])

# np.searchsorted()
- Used to find where a value should be inserted in a sorted array.

In [39]:
arr=np.array([1,20,30,40,20,40,50,50,60])
result=np.searchsorted(arr,25)
print(result)

5


# Search multiple values

In [42]:
arr=np.array([10,20,30,40,50,60,90])
result=np.searchsorted(arr,[10,60,90])
print(result)

[0 5 6]


# Sorting a 2D array

In [44]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [48]:
# Sort columns using axis=0
print(np.sort(arr, axis=0))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [49]:
# Sort rows using axis=1
print(np.sort(arr, axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [52]:
# Real Example — Student Ranking
students = np.array([
    "Sandeep",
    "Ravi",
    "Asha",
    "Neha",
    "Kiran"])
marks = np.array([78, 92, 85, 95, 70])
print(students)
print(marks)

['Sandeep' 'Ravi' 'Asha' 'Neha' 'Kiran']
[78 92 85 95 70]


In [53]:
ranking = np.argsort(marks)[::-1]
print(students[ranking])
print(marks[ranking])

['Neha' 'Ravi' 'Asha' 'Sandeep' 'Kiran']
[95 92 85 78 70]


# Real Example — Product Prices

In [54]:
products = np.array([
    "Laptop",
    "Mouse",
    "Keyboard",
    "Monitor",
    "Headphones"])

prices = np.array([
    60000,
    1200,
    2500,
    15000,
    3000])

In [55]:
indices = np.argsort(prices)
print(products[indices])
print(prices[indices])

['Mouse' 'Keyboard' 'Headphones' 'Monitor' 'Laptop']
[ 1200  2500  3000 15000 60000]
