# Day 04 — NumPy Slicing
- Slicing is used to extract a portion of an array using start, stop and step.
- array[start : stop : step]

# Basic 1D Slicing

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [6]:
print(arr[1:4])

[2 3 4]


# First 3 Elements

In [8]:
print(arr[:3])

[1 2 3]


# From Index 2 to End

In [9]:
print(arr[2:])

[3 4 5 6 7]


# Copy First 4 Elements

In [11]:
print(arr[:4])

[1 2 3 4]


# Last 3 Elements

In [12]:
print(arr[-3])

5


# Remove Last 2 Elements

In [13]:
print(arr[:-2])

[1 2 3 4 5]


# Every 2nd Element

In [15]:
print(arr[::2])

[1 3 5 7]


# Every 3rd Element

In [16]:
print(arr[::3])

[1 4 7]


# Reverse an Array 

In [17]:
print(arr[::-1])

[7 6 5 4 3 2 1]


# Reverse Part of Array

In [19]:
print(arr[4:1:-1])

[5 4 3]


# 2D Array Slicing

In [26]:
import numpy as np
arr2=np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]])
print(arr2)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [27]:
print(arr.shape)

(3, 4)


# Get First Row

In [28]:
print(arr[0,:])

[10 20 30 40]


In [32]:
print(arr2[0])

[10 20 30 40]


# Get Second Row

In [35]:
print(arr[1,:])

[50 60 70 80]


# Get First Column

In [36]:
print(arr2[:,0])

[10 50 90]


# Get Second Column

In [37]:
print(arr2[:,1])

[ 20  60 100]


In [38]:
# Get Last Column
print(arr2[:,-1])

[ 40  80 120]


# Get First 2 Rows

In [39]:
print(arr2[:2,:])

[[10 20 30 40]
 [50 60 70 80]]


# Get Last 2 Rows

In [41]:
print(arr2[-2:,:])

[[ 50  60  70  80]
 [ 90 100 110 120]]


# Get First 2 Columns

In [42]:
print(arr2[:,:2])

[[ 10  20]
 [ 50  60]
 [ 90 100]]


# Get Last 2 Columns

In [43]:
print(arr2[:,-2:])

[[ 30  40]
 [ 70  80]
 [110 120]]
