# What is np.unique
- np.unique() returns only the distinct values from an array and removes duplicates.

In [3]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,70,80])
result=np.unique([arr])
print(result)

[10 20 30 40 50 60 70 80]


In [5]:
# Example 1: Student marks

marks=np.array([80,60,70,70,80,80,50,70,60])
print(np.unique(marks))

[50 60 70 80]


In [7]:
# 2 Employee departments
departments = np.array(["IT", "HR", "IT", "Sales", "HR", "IT"])
print(np.unique(departments))

['HR' 'IT' 'Sales']


In [9]:
# Example 3: Product categories

products = np.array(["Mobile", "Laptop", "Mobile","Tablet", "Laptop", "Mobile"])
print(np.unique(products))

['Laptop' 'Mobile' 'Tablet']


# Count frequency using return_counts=True

In [12]:
arr=np.array([10,20,30,10,30,40,50,40,10])
values,count=np.unique(arr,return_counts=True)
print("Values:",values)
print("Count:",count)

Values: [10 20 30 40 50]
Count: [3 1 2 2 1]


# Real-time example — Count student grades

In [13]:
grades = np.array([
    "A", "B", "A", "C", "B",
    "A", "A", "C", "B", "A"])
grade_names, grade_counts = np.unique(grades,return_counts=True)
print("Grades:", grade_names)
print("Frequency:", grade_counts)

Grades: ['A' 'B' 'C']
Frequency: [5 3 2]


# Find the most frequent value

In [16]:
values, counts = np.unique(grades, return_counts=True)
index = np.argmax(counts)
print("Most frequent grade:", values[index])
print("Frequency:", counts[index])

Most frequent grade: A
Frequency: 5


# Frequency counting with np.bincount()
- np.bincount() counts occurrences of non-negative integers, including integers that do not appear in the array.

In [17]:
numbers = np.array([1, 2, 2, 3, 3, 3, 5])
counts = np.bincount(numbers)
print(counts)

[0 1 2 3 0 1]
