# NumPy Array Joining

In [3]:
import numpy as np
arr1=np.array([10,20,30,40])
arr2=np.array([40,50,60,70])
print(arr1)
print(arr2)

[10 20 30 40]
[40 50 60 70]


# 2. np.concatenate()
- It combines two arrays into one array.

In [6]:
import numpy as np
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
result=np.concatenate((arr1,arr2))
print(result)

[10 20 30 40 50 60 70 80]


In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(np.concatenate((a,b)))
print(np.concatenate((a,b,c)))

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


# 3. np.vstack() — Vertical joining

In [18]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
result=np.vstack((arr1,arr2))
print(result)
print(result.shape)
print(result.dtype)

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
int64


In [20]:
std1=np.array([60,70,76])
std2=np.array([55,78,94])
marks=np.vstack((std1,std2))
print(marks)

[[60 70 76]
 [55 78 94]]


# 4. np.hstack() — Horizontal joining
- For one-dimensional arrays, hstack() joins the values into one longer array.

In [22]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])
result=np.hstack((arr1,arr2))
print(result)

[ 10  20  30  40  50  60  70  80  90 100]


In [26]:
# Real-time example: Sales data
week1=np.array([10000,20000,30000,40000])
week2=np.array([50000,60000,70000,80000])
total_data=np.hstack((week1,week2))
print(total_data)

[10000 20000 30000 40000 50000 60000 70000 80000]


# 5. Important difference for 2D arrays

In [27]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print("Concatenate axis=0:")
print(np.concatenate((a, b), axis=0))

print("Concatenate axis=1:")
print(np.concatenate((a, b), axis=1))

print("Vertical:")
print(np.vstack((a, b)))

print("Horizontal:")
print(np.hstack((a, b)))

Concatenate axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate axis=1:
[[1 2 5 6]
 [3 4 7 8]]
Vertical:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal:
[[1 2 5 6]
 [3 4 7 8]]
