#  NumPy Random Functions

In [2]:
# 1. Import NumPy
import numpy as np

In [6]:
# 2. np.random.randint() — Random integers
import numpy as np
arr = np.random.randint(1, 100, size=5)
print(arr)

[63 77 56 89 24]


In [8]:
# 3. Generate a 1D array
arr=np.random.randint(3,10,size=10)
print(arr)

[3 5 3 9 4 6 6 8 5 7]


# 4. Generate a 2D array

In [10]:
arr=np.random.randint(1,100,size=(3,4))
print(arr)

[[83 96  3 12]
 [20 75 28  3]
 [72  9 99 50]]


# 5. np.random.rand() — Random decimal numbers
- Generates random decimal values between 0 and 1.

In [11]:
arr=np.random.rand(5)
print(arr)

[0.82581955 0.99856039 0.79336523 0.10756212 0.22172308]


In [12]:
# Generate a 2D array:
arr=np.random.rand(3,4)
print(arr)

[[0.02799954 0.157334   0.14908059 0.96070397]
 [0.3660518  0.67818954 0.15758076 0.48973966]
 [0.61868603 0.70801637 0.19530888 0.07264017]]


# 6. np.random.randn() — Standard normal distribution
- Generates values from a standard normal distribution, with mean approximately 0 and standard deviation approximately 1.

In [13]:
arr=np.random.randn(5)
print(arr)

[-0.48479811  1.4071087   0.04113166  0.89366679  0.82150124]


In [15]:
# 7. np.random.random() — Random decimal values
arr=np.random.random(5)
print(arr)

[0.9543489  0.55205502 0.78640627 0.23887791 0.74276761]


# 8. np.random.choice() — Select random values

In [16]:
marks=np.array([45,50,60,55,70,80,70,92])
result=np.random.choice(marks,size=5)
print(result)

[80 50 92 70 92]


In [17]:
result = np.random.choice(marks, size=3, replace=False)
print(result)

[80 45 60]


# 9. np.random.shuffle() — Shuffle an array

In [20]:
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)

[20 50 30 10 40]


# 10. np.random.permutation() — Random rearrangement

In [21]:
arr=np.array([10,20,30,40,50,60])
result=np.random.permutation(arr)
print(result)

[30 50 40 10 60 20]


# 11. np.random.seed() — Reproducible results

In [22]:
np.random.seed(42)
arr = np.random.randint(1, 100, size=5)
print(arr)

[52 93 15 72 61]


In [24]:
rng = np.random.default_rng(42)
arr = rng.integers(1, 100, size=5)
print(arr)

[ 9 77 65 44 43]


# 12. Real-life example — Student marks analysis

In [26]:
import numpy as np
rng = np.random.default_rng(42)
marks = rng.integers(0, 101, size=10)
print("Student Marks:", marks)
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Passed Students:", np.sum(marks >= 40))
print("Failed Students:", np.sum(marks < 40))

Student Marks: [ 9 78 66 44 43 86  8 70 20  9]
Average Marks: 43.3
Highest Marks: 86
Lowest Marks: 8
Passed Students: 6
Failed Students: 4


# 13. Real-life example — Sales data

In [27]:
rng = np.random.default_rng(42)
sales = rng.integers(1000, 10001, size=7)
print("Weekly Sales:", sales)
print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Maximum Sales:", np.max(sales))
print("Minimum Sales:", np.min(sales))

Weekly Sales: [1803 7966 6891 4950 4897 8728 1773]
Total Sales: 37008
Average Sales: 5286.857142857143
Maximum Sales: 8728
Minimum Sales: 1773
