# Create a 1D Array

In [1]:
import numpy as np

In [16]:
arr=np.array([10,20,30,40,50,60])
print(arr)
print("Shape:",arr2.shape)
print(arr2.dtype)

[10 20 30 40 50 60]
Shape: (6,)
int64


# reshape()
- We can convert the 1D array into a 2D array.

In [20]:
arr2=arr.reshape(2,3)
print(arr2)

[[10 20 30]
 [40 50 60]]


In [22]:
print(arr2.shape) # 2 rows × 3 columns

(2, 3)


# Reshape into 3 × 2

In [26]:
arr2=arr.reshape(3,2)
print(arr2)

[[10 20]
 [30 40]
 [50 60]]


# Reshape into 6 × 1

In [29]:
arr2=arr.reshape(6,1)
print(arr2)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


# Using -1 in reshape 
- NumPy can automatically calculate one dimension.

In [31]:
arr2=arr.reshape(2,-1)
print(arr2)

[[10 20 30]
 [40 50 60]]


In [35]:
arr2=arr.reshape(-1, 2)
print(arr2)

[[10 20]
 [30 40]
 [50 60]]


# flatten()
- flatten() converts a multi-dimensional array into 1D.

In [36]:
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]])

flat = arr2.flatten()
print(flat)

[10 20 30 40 50 60]


In [38]:
print(flat.shape)

(6,)


# ravel()
- ravel() also converts a multi-dimensional array into 1D.

In [42]:
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]])
result = arr2.ravel()
print(result)

[10 20 30 40 50 60]


In [43]:
arr.reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

In [46]:
arr2.flatten()

array([10, 20, 30, 40, 50, 60])

# resize()
- resize() can change the size of an array

In [49]:
arr=np.array([10,20,30,40,50,60])
arr.resize(2,2)
print(arr)

[[10 20]
 [30 40]]


In [52]:
arr=np.array([10,20,30,40,50])
arr.resize(3,2)
print(arr)

[[10 20]
 [30 40]
 [50  0]]


# Suppose you have 12 student marks

In [59]:
marks = np.array([
    80, 75, 90, 85,
    70, 65, 88, 92,
    78, 82, 95, 89])

In [60]:
marks.resize(3,4)
print(marks)

[[80 75 90 85]
 [70 65 88 92]
 [78 82 95 89]]


In [61]:
print(marks.shape)

(3, 4)
