# 1. Create a NumPy array

In [1]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50,])

In [4]:
print("Array:",arr)

Array: [10 20 30 40 50]


In [9]:
# 2. Shape
print("Shape:",arr.shape)

Shape: (5,)


In [11]:
# 3. Size
print("Size:",arr.size)

Size: 5


In [13]:
# 4. Number of dimensions
print("Dimensions:",arr.ndim)

Dimensions: 1


In [36]:
# 5. Data type
print("Data_type:",arr.dtype)

Data_type: int64


# create a 2D array:

In [22]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array:",arr2)

Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
print("Shape:",arr2.shape)

Shape: (2, 5)


In [27]:
print("Size:",arr2.size)

Size: 10


In [29]:
print("Dimensions:",arr.dtype)

Dimensions: int64


# NumPy 3D Array

In [32]:
import numpy as np
arr3= np.array([[[10, 20, 30],[40, 50, 60]],[[70, 80, 90],[100, 110, 120]]])
print(arr)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [33]:
print("Shape:",arr3.shape)

Shape: (2, 2, 3)


In [34]:
print("Size:",arr3.size)

Size: 12


In [37]:
print("Dimesions:",arr3.ndim)

Dimesions: 3
